question_data = {
    "computers": [
        {"category": "Science: Computers",
         "type": "boolean",
         "difficulty": "easy",
         "question": "Linus Torvalds created Linux and Git.",
         "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"category": "Science: Computers",
         "type": "boolean",
         "difficulty": "easy",
         "question": "The programming language \"Python\" is based off a modified version of \"JavaScript\".",
         "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"category": "Science: Computers",
         "type": "boolean",
         "difficulty": "easy",
         "question": "The logo for Snapchat is a Bell.",
         "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"category": "Science: Computers",
         "type": "boolean",
         "difficulty": "easy",
         "question": "Ada Lovelace is often considered the first computer programmer.",
         "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"category": "Science: Computers",
         "type": "boolean",
         "difficulty": "easy",
         "question": "\"HTML\" stands for Hypertext Markup Language.",
         "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
         "question": "Time on Computers is measured via the EPOX System.",
         "correct_answer": "False",
         "incorrect_answers": ["True"]},
        {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
         "question": "The Windows 7 operating system has six main editions.",
         "correct_answer": "True", "incorrect_answers": ["False"]},
        {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
         "question": "The Windows ME operating system was released in the year 2000.",
         "correct_answer": "True",
         "incorrect_answers": ["False"]},
        {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
         "question": "Linux was first created as an alternative to Windows XP.",
         "correct_answer": "False", "incorrect_answers": ["True"]},
        {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
         "question": "The Python programming language gets its name from the British comedy group \"Monty Python's "
                     "Flying "
                     "Circus\"",
         "correct_answer": "True", "incorrect_answers": ["False"]}],
    "anime": [{"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "easy",
               "question": "In the 1988 film \"Akira\", Tetsuo ends up destroying Tokyo.",
               "correct_answer": "True",
               "incorrect_answers": ["False"]},
              {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "easy",
               "question": "Clefairy was intended to be Ash starting Pokemon in the pilot episode of the cartoon.",
               "correct_answer": "True", "incorrect_answers": ["False"]},
              {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "easy",
               "question": "Studio Ghibli is a Japanese animation studio responsible for the films \"Wolf Children\" "
                           "and \"The Boy and the Beast\".",
               "correct_answer": "False", "incorrect_answers": ["True"]},
              {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "easy",
               "question": "In Kill La Kill, the weapon of the main protagonist is a katana. ",
               "correct_answer": "False",
               "incorrect_answers": ["True"]},
              {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "easy",
               "question": "The anime \"Lucky Star\" follows the story of one girl who is unaware she is God.",
               "correct_answer": "False", "incorrect_answers": ["True"]},
              {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "easy",
               "question": "No Game No Life first aired in 2014.", "correct_answer": "True",
               "incorrect_answers": ["False"]},
              {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "easy",
               "question": "In the \"Melancholy of Haruhi Suzumiya\" series, the narrator goes by the nickname Kyon.",
               "correct_answer": "True", "incorrect_answers": ["False"]},
              {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "easy",
               "question": "The name of the attack \"Kamehameha\" in Dragon Ball Z was named after a famous "
                           "king of Hawaii.",
               "correct_answer": "True", "incorrect_answers": ["False"]},
              {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "easy",
               "question": "In the \"To Love-Ru\" series, Golden Darkness is sent to kill Lala Deviluke.",
               "correct_answer": "False", "incorrect_answers": ["True"]},
              {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "easy",
               "question": "In Chobits, Hideki found Chii in his apartment.", "correct_answer": "False",
               "incorrect_answers": ["True"]}],
    "videogame": [{"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                   "question": "Peter Molyneux was the founder of Bullfrog Productions.", "correct_answer": "True",
                   "incorrect_answers": ["False"]},
                  {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                   "question": "The song \"Megalovania\" by Toby Fox made its third appearence in the 2015 RPG "
                               "\"Undertale\".",
                   "correct_answer": "True", "incorrect_answers": ["False"]},
                  {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                   "question": "Donkey Kong was originally set to be a Popeye arcade game.", "correct_answer": "True",
                   "incorrect_answers": ["False"]},
                  {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                   "question": "In \"Sonic Adventure\", you are able to transform into Super Sonic at will after "
                               "completing the main story.",
                   "correct_answer": "False", "incorrect_answers": ["True"]},
                  {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                   "question": "Deus Ex (2000) does not feature the World Trade Center because it was destroyed by "
                               "terrorist attacks according to the game&#039;s plot.",
                   "correct_answer": "True", "incorrect_answers": ["False"]},
                  {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                   "question": "The main playable character of the 2015 RPG \"Undertale\" is a monster.",
                   "correct_answer": "False", "incorrect_answers": ["True"]},
                  {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                   "question": "In Splatoon, the Squid Sisters are named Tako and Yaki.", "correct_answer": "False",
                   "incorrect_answers": ["True"]},
                  {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                   "question": "Valve&#039;s \"Portal\" and \"Half-Life\" franchises exist within the "
                               "same in-game universe.",
                   "correct_answer": "True", "incorrect_answers": ["False"]},
                  {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                   "question": "In Until Dawn, both characters Sam and Mike cannot be killed under any means until the "
                               "final chapter of the game.",
                   "correct_answer": "True", "incorrect_answers": ["False"]},
                  {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                   "question": "There are 2 player roles in Trouble in Terrorist Town.", "correct_answer": "False",
                   "incorrect_answers": ["True"]}]
}
